#!/bin/bash

# load environment
source activate openmm

filepath='data/input/241010_FUB/p53/p53_1.pdb'
python ../../src/plumed/main.py --filepath "../../$filepath" --device_index 1 --timestep 2 --mdtime 1.0 --barrier 100 --restart_rfile 'OPES_100ns/p53_1/p53_1.state'
