#!/bin/bash

# load environment
source activate openmm

SYSTEM_NAME='p53_1'
FILEPATH="data/input/241010_FUB/$SYSTEM_NAME/$SYSTEM_NAME.pdb"
python ../../src/plumed/main.py --filepath "../../$FILEPATH" --device_index 0 --timestep 2 --mdtime 500 --barrier 200 --restart_rfile "OPES_100ns/$SYSTEM_NAME/$SYSTEM_NAME.state"
