name: base
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - openmm=8.2
  - cudatoolkit=11.8
  - numpy=1.26.4
  - swig
  - pip
  - numba
  - pdbfixer
  - biopython
  - matplotlib
  - mdanalysis
  - fire
  - h5py
  - cmake
  - git
  - make
  - gcc
  - gxx
  - notion-client
  - python-dotenv
  - pydantic
  - hydra-core
  - openmmtools
  - ruff
  - pip
  - rdkit
  - pip:
    - openmm-mdanalysis-reporter
    - mdtraj