name: base
channels:
  - conda-forge
dependencies:
  - python=3.12
  - openmm=8.2
  - swig
  - pip
  - numpy
  - numba
  - pdbfixer
  - biopython
  - matplotlib
  - mdtraj
  - fire
  - h5py
  - cmake
  - git
  - make
  - gcc
  - gxx
  - notion-client
  - python-dotenv