#!/bin/bash
#PBS -l walltime=12:00:00
#PBS -l select=1:ncpus=1:mem=80gb:ngpus=1:gpu_type=A100
#PBS -q hx
#PBS -l place=excl
#PBS -N openmm.md

cd $PBS_O_WORKDIR
cat $PBS_NODEFILE

module load CUDA/11.8.0

export LD_LIBRARY_PATH=/gpfs/home/jl24018/mambaforge-pypy3/envs/openmm/lib:$LD_LIBRARY_PATH

# load environment
# source activate openmm-debug
source activate openmm-debug-2

filepath='data/input/241010_FUB/p53/p53_1.pdb'
python ../../src/main.py --filepath "../../$filepath" --device_index 0 --timestep 2 --mdtime 2

