python run.py \
    --filepath "../../data/241010_FoldingUponBinding/input/A-synuclein/A-synuclein_alpha.pdb" \
    --system "ASYN-A" \
    --biasfactor 56 \
    --sigma_cv1 "0.24" \
    --sigma_cv2 "0.05" \
    --grid_min_cv1 "0" \
    --grid_max_cv1 "90" \
    --grid_min_cv2 "0" \
    --grid_max_cv2 "7" \
    --output_dir "../../data/241010_FoldingUponBinding/output/ASYN-A/241128-Test"